# The book's title. Will be used everywhere!
title: "Kitabu"

# The book's language.
language: en

# Your book copyright info.
# Here's some examples:
#
#   Copyright 2019 by Elomar Nascimento dos Santos.
#   Copyright 2019 by Elomar Nascimento dos Santos. This work is licensed under MIT License.
#   This work is licensed under a Creative Commons Attribution-ShareAlike 3.0 Unported License.
#   This work is licensed under a Creative Commons Attribution-NonCommercial-NoDerivs 3.0 Unported License.
#   This work is licensed under a Creative Commons Attribution-NonCommercial-ShareAlike 3.0 Unported License.
#
copyright: "Copyright (C) 2019 Elomar Nascimento dos Santos."

# Who's publishing this book.
publisher: "Elomar Nascimento dos Santos"

# When this book was published.
published_at: "2019-11-08"

# Some book description.
subject: "This guide will help you understand how all of the pieces fit together on Kitabu."

# Some keywords that identify this book.
keywords: "kitabu, e-book, kindlegen, epub, mobi, pdf, prince"

# Some unique identification. Works great with your domain
# like `http://yourbook.example.com`.
uid: "9b302983a0b93893c385c1235a6e1aab"

# Your book identification like ISBN or ISSN.
identifier:
  id: "http://yourbook.example.com"
  type: "URL" # can be ISBN, ISSN or URL

# This book authors.
authors:
  - "Elomar Nascimento dos Santos"

# Syntax highlight theme. Can be any of supported by Rouge.
theme: github
