title: "100 Pages of Elixir"
language: en
copyright: "Copyright 2019 by Elomar Nascimento dos Santos. This work is licensed under MIT License."

publisher: "Elomar Nascimento dos Santos"
published_at: "2019-11-08"

subject: "This book is about the basic concepts of Elixir."
keywords: "elixir, erlang, programming, functional programming"

uid: "https://100pages.io/elixir"
identifier:
  id: "https://100pages.io/elixir"
  type: "URL"

authors:
  - "Elomar Nascimento dos Santos"

theme: github
